version: '3.1'

services:
    mariadb:
        image: mariadb:latest
        env_file: mariadb/.env
        volumes:
            - type: bind
              source: ./mariadb/data
              target: /var/lib/mysql

    web:
        build:
            context: ./web
        depends_on:
            - mariadb
        env_file: web/.env
        volumes:
            - type: bind
              source: ./web/documents
              target: /var/www/documents
        ports:
            - "80:80"
